### ISSUE TITLE
Actividad 1: mapa mental 

### ISSUE THREAD

**Issue by MarleneRamirez0731** [SistemasTecTlaxiaco/actividad-1-mapa-mental-MarleneRamirez0731#2]
Marlene Maricela Osorio Ramírez 1° BS 
Actividad 1: mapa mental 

![png_20220901_160305_0000](https://user-images.githubusercontent.com/112357070/188022237-3f52ed04-80da-46c1-8543-5627e545e6cb.png)

**Comment by gilbertovelasco1** [comment]
17%

**Comment by gilbertovelasco1** [comment]
19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
